source 'https://rubygems.org'

gem 'berkshelf'
gem 'chefspec'
gem 'foodcritic'
gem 'inspec'
gem 'kitchen-docker'
gem 'kitchen-inspec'
gem 'knife-solo_data_bag'
gem 'rake'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rubocop'
gem 'rubocop-checkstyle_formatter'
gem 'serverspec'
gem 'stove'
gem 'test-kitchen'
